#pragma once

#define _USE_MATH_DEFINES
#include <Windows.h>
#include <gdiplus.h>
#include <GLFW/glfw3.h>
#include <stdio.h>
#include <tchar.h>
#include <math.h>
#include <assert.h>
#include <string>
#include <stdexcept>
#include <GL/glu.h>
//#include <GL/glut.h>
#include <chrono>
#include <cmath>
#include <glm/ext/matrix_clip_space.hpp>
#include <glm/ext/matrix_transform.hpp>
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/ext.hpp>
#pragma comment(lib,"gdiplus.lib")
#include <stdexcept>
